### ISSUE TITLE
Myst build Pdf: TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by dressedfez** [executablebooks/mystjs#325]
### What version of `mystjs` are you using?

v0.1.19

### How did you install myst?

npm

### What operating system are you using?

Mac

### Which area is this feature request for?

Export: LaTeX or PDF

### Describe the Bug

<img width="686" alt="Bildschirm­foto 2023-03-25 um 09 13 42" src="https://user-images.githubusercontent.com/5203474/227705750-7be35914-3e04-4333-9ac5-694cce9bfb66.png">

Using `myst start` everything works fine and the paper is shown correctly.

The paper is here:
[paper-example.zip](https://github.com/executablebooks/mystjs/files/11068376/paper-example.zip)

### Expected Behavior

The pdf output of the paper is created. 

### To Reproduce

1. Unzip the appended paper
2. Change into the corresponding subdirectory
3. run `myst build paper.md --pdf`

**Comment by rowanc1** [comment]
Thanks for the report @dressedfez !

Do you think that you could run the command again with the `-d` flag, this will print a bit more about the error.

**Comment by dressedfez** [comment]
Here is the output:
![Bildschirm­foto 2023-03-25 um 18 13 09](https://user-images.githubusercontent.com/5203474/227731856-4db27ad7-6c89-43fe-a3b4-560f537bb5ad.png)

**Comment by riziles** [comment]
> Here is the output:

@dressedfez , what do the percent signs do on e.g. lines 73 and 74? They seem to be part of the problem.

**Comment by riziles** [comment]
@rowanc1 probably worth noting in the docs unless it's a very easy code fix.

**Comment by dressedfez** [comment]
I can confirm that the removing the percentage symbols without anything else in the line allows me to build the PDF.
I have introduced those percentage symbols to avoid empty lines in LaTex (as far as I can remember). We have written this article in 2004 or so my brain trick me here.

As a user I would expect here more information. In my case I did not even see logs from LaTex process.

**Comment by riziles** [comment]
> As a user I would expect here more information. In my case I did not even see logs from LaTex process.

As a user, I would tend to agree with you, but the MyST CLI is still pretty awesome for a free open-source 1 year old beta project. Thanks, @rowanc1 !

**Comment by dressedfez** [comment]
I want to underline here that I'm as well very happy that the project has been open sourced. I'm as well aware that this is still in beta phase. 

As a user of software, whether it is open-source or commercial, I'm happy to provide feedback to make the software better. This is in the interest of everybody. From my point of few the issue is resolved, but I would suggest to still look at this topic since it is a valid  scenario that one takes an old LaTex article, which might contain % symbols as comments, and tries to convert it to Myst markdown. 

Again, great job @rowanc1 and rest of the team and I'm happy to support it in my free time.

**Comment by fwkoch** [comment]
Thanks for the issue and the follow up! This is great!

Looks like the `TypeError` message was a small bug where empty MyST comments (i.e. lines with only `%`) were not handled correctly. I fixed this up in #326 - Once that PR is landed, the "myst comment" becomes a "LaTeX comment" i.e. the standalone `%` is persisted.

When running your example paper, I still see some errors, but it looks like they are directly from the LaTeX build.

**Comment by dressedfez** [comment]
> Thanks for the issue and the follow up! This is great!
> 
> Looks like the `TypeError` message was a small bug where empty MyST comments (i.e. lines with only `%`) were not handled correctly. I fixed this up in #326 - Once that PR is landed, the "myst comment" becomes a "LaTeX comment" i.e. the standalone `%` is persisted.
> 
> When running your example paper, I still see some errors, but it looks like they are directly from the LaTeX build.

This is correct and I have already fixed them for the template I have been working in the last few days. In case of the lapreprint template some fonts are missing for the particular article, but this no issue for me. The article was published in PRL and I wanted to see how closely I can reproduce the original publication. It really looks promising.
